import { Contact } from '@/components/Contact'
import { CreateYourEcommerce } from '@/components/CreateYourEcommerce'
import { FAQS } from '@/components/FAQS'
import { Hero } from '@/components/Hero'
import { MyProjects } from '@/components/MyProjects'
import { LayoutGroup } from 'framer-motion'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-x-hidden"> 
        <Hero />
        <CreateYourEcommerce />
        <MyProjects />
        <LayoutGroup>
          <FAQS />
          <Contact />
        </LayoutGroup>
      </main>
    </>
  )
}
